spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/t734070824/springcloud/tree
          search-paths: git-config
          username: t734070824
          password: t05575341338
server:
  port: 7001