spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1
server:
  port: 1111
eureka:
  instance:
    hostname: peer1
    # 服务器续约任务的调用间隔 reload
    lease-renewal-interval-in-seconds: 30
    # 服务失效时间
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://peer2:1111/eureka/
    fetch-registry: true
    register-with-eureka: true
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2
server:
  port: 1112
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/
    fetch-registry: true
    register-with-eureka: true